project:
  type: website
  resources: 
  - resume.pdf

website:
  title: "Jeremy Reyes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects

format:
  html:
    theme:
      - solar
      - brand
    css: styles.css
    toc: false

editor: visual

